In [3]:
import pandas as pd
import pickle
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
preprocess_model = pickle.load(open('preprocess_model.pkl','rb'))

In [6]:
x_train = preprocess_model[0]
y_train = preprocess_model[1]
x_test = preprocess_model[2]
y_test = preprocess_model[3]

## Linear Regression

In [7]:
from sklearn.linear_model import LinearRegression
regression = LinearRegression()
regression.fit(x_train,y_train)

LinearRegression()

In [8]:
print(regression.coef_)
print(regression.intercept_)

[ 245.9262922    -1.02400377    1.39451704 -138.1132785 ]
310.50178446771366


In [9]:
# prediction for test data
reg_pred= regression.predict(x_test)

In [10]:
reg_pred

array([353.63149789, 144.37260091, 314.31022679, 281.60696616,
       222.55622156, 305.53238724, 276.27220792, 437.2683665 ,
       399.52437522,  64.48959208, 540.77162981, 230.25601943,
       466.14408522, 292.52182869, 183.51897185, 222.99965851,
       299.94556563, 262.70042801, 187.90935764, 362.05976127,
       368.92491204, 185.97881449, 437.6401434 , 331.93512692,
       276.25795557, 224.57104418, 239.1844413 , 365.63047116,
       239.93328707, 371.78431266, 421.64665497, 365.74265193,
       464.28379523, 260.16793436, 581.77718027, 205.4875672 ,
       100.21756709, 159.17957004, 414.59031095, 228.86464049,
       568.29315277, 286.25996791,  11.3545994 , 357.5277879 ,
       318.84209577, 415.29869351, 276.90654115, 225.22663644,
       231.85898143, 374.51681962, 119.4525647 , 381.10876252,
       298.80966641, 420.40511984, 280.37672541, 542.52919291,
       379.71650421, 210.92326855, 184.06487428, 252.93775767,
       179.15088905, 325.2712091 ,  60.25775005, 330.15

In [12]:
# R2 score or R-squared score
from sklearn.metrics import r2_score
linear_r2 = r2_score(y_test,reg_pred)
print(linear_r2)

0.9842291794665293


In [13]:
# adjusted R square score
adjusted_linear_r2 = 1 - (1-linear_r2)*(len(y_test)-1)/(len(y_test)-x_test.shape[1]-1)
adjusted_linear_r2

0.9840938076164566

## Ridge regression

In [14]:
from sklearn.linear_model import Ridge
ridge = Ridge()
ridge.fit(x_train,y_train)

Ridge()

In [15]:
ridge_pred = ridge.predict(x_test)

In [16]:
ridge_pred

array([353.86868805, 144.8574234 , 314.19028877, 281.75562766,
       223.85939179, 306.58794978, 276.84355455, 436.84890959,
       398.64996828,  65.06051472, 540.28971051, 230.98029889,
       464.70218886, 292.62627041, 184.76082436, 223.99603512,
       301.67751532, 263.42439836, 188.53979014, 360.84376096,
       368.59057761, 186.17634446, 438.01514508, 331.90122457,
       277.75571249, 225.11106473, 239.71110751, 365.08258755,
       240.12127656, 371.86647509, 420.39983822, 366.31765239,
       463.50983848, 259.51397747, 579.93399457, 205.80556648,
       100.67251864, 160.02908987, 413.01902951, 230.64144502,
       566.77676385, 287.55618589,  12.1072121 , 357.23567959,
       318.13097282, 415.51134983, 277.54486051, 225.91613148,
       232.07112979, 374.12118374, 120.23424523, 381.23458628,
       299.83198873, 420.17670938, 281.65484995, 541.72057331,
       380.67539343, 211.74381562, 184.4296232 , 255.04028739,
       180.21973647, 325.49455628,  60.98422457, 330.22

In [17]:
# Let's see the R2 score for Ridge
from sklearn.metrics import r2_score
ridge_r2 = r2_score(y_test,ridge_pred)
print(ridge_r2)

0.984080169953393


In [18]:
# let's see the Adjusted R2 score
adjusted_ridge_r2 = 1 - (1-ridge_r2)*(len(y_test)-1)/(len(y_test)-x_test.shape[1]-1)
adjusted_ridge_r2 

0.9839435190517054

## Lasso regression

In [19]:
from sklearn.linear_model import Lasso
lasso = Lasso()
lasso.fit(x_train,y_train)

Lasso()

In [20]:
lasso_pred = lasso.predict(x_test)

In [21]:
# R2 score for Lasso
from sklearn.metrics import r2_score
lasso_r2 = r2_score(lasso_pred,y_test)
lasso_r2

0.980995851856877

In [22]:
# Adjusted R2 score for Lasso
adjusted_lasso_r2 = 1 - (1-lasso_r2)*(len(y_test)-1)/(len(y_test)-x_test.shape[1]-1)
adjusted_lasso_r2

0.9808327261217429

## Elasticnet Regression

In [23]:
from sklearn.linear_model import ElasticNet
elastic = ElasticNet()
elastic.fit(x_train,y_train)

ElasticNet()

In [24]:
elastic_pred=elastic.predict(x_test)

In [25]:
elastic_pred

array([369.885497  , 192.45565485, 316.67859621, 307.30002609,
       329.34701417, 372.68401992, 335.43630023, 387.52680415,
       315.09000747, 139.18965359, 459.70519549, 293.42948724,
       336.61182333, 293.7841909 , 291.84657037, 299.51236037,
       406.2783315 , 335.26998654, 255.03135699, 268.05174383,
       328.58191596, 228.175546  , 438.8577369 , 327.49765229,
       386.69754911, 278.60663395, 279.7933016 , 315.61961837,
       270.41982575, 363.62083384, 326.48435807, 389.65077206,
       383.63235546, 224.06267669, 410.77208391, 239.33651519,
       164.94633857, 238.87644854, 284.06519177, 363.95265144,
       429.56104465, 374.23892287,  99.18094034, 327.97382126,
       278.67040566, 402.85088796, 321.61646818, 299.93900462,
       264.99054226, 332.29118281, 200.44512789, 385.38007177,
       358.1446847 , 377.09355679, 367.04322455, 443.503426  ,
       427.65220432, 284.17094907, 222.91672473, 404.8836648 ,
       264.39457472, 331.99192134, 151.07892655, 345.13

In [26]:
#R squared

from sklearn.metrics import r2_score
elasticnet_r2=r2_score(lasso_pred,y_test)
elasticnet_r2

0.980995851856877

In [27]:
# Adjusted R square

adjusted_elasticnet_r2 = 1 - (1-elasticnet_r2)*(len(y_test)-1)/(len(y_test)-x_test.shape[1]-1)
adjusted_elasticnet_r2

0.9808327261217429